"use client";

import { SUPPORT_TEXT_LIMITS } from "@/config/support-text-contract";
import { useRef, useState, type FormEvent } from "react";

export function ContactForm() {
  const requestIdRef = useRef<string | null>(null);
  const [category, setCategory] = useState("general"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [status, setStatus] = useState(""); const [receiptId, setReceiptId] = useState(""); const [threadUrl, setThreadUrl] = useState(""); const [saving, setSaving] = useState(false);
  const messageTooLong = message.length > SUPPORT_TEXT_LIMITS.reply;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (messageTooLong) { setStatus(`内容は${SUPPORT_TEXT_LIMITS.reply.toLocaleString()}文字以内にしてください。`); return; } setSaving(true); setStatus(""); setReceiptId(""); setThreadUrl(""); try { requestIdRef.current ??= crypto.randomUUID(); const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ requestId: requestIdRef.current, category, name, email, message }) }); const data = await response.json().catch(() => null) as { contact?: { id?: string }; thread?: { url?: string }; error?: string; limit?: number } | null; if (!response.ok) { if (data?.error === "support_text_too_long") { setStatus(`内容は${(data.limit ?? SUPPORT_TEXT_LIMITS.reply).toLocaleString()}文字以内にしてください。`); return; } throw new Error(); } requestIdRef.current = null; setMessage(""); setReceiptId(data?.contact?.id ?? ""); setThreadUrl(data?.thread?.url ?? ""); setStatus("送信しました。内容を確認のうえ対応します。"); } catch { setStatus("送信できませんでした。時間をおいてもう一度お試しください。"); } finally { setSaving(false); } };
  return <form onSubmit={submit} className="mt-7 space-y-4">
    <label className="block text-sm font-bold">お問い合わせ種別<select value={category} onChange={(event) => { requestIdRef.current = null; setCategory(event.target.value); }} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 font-normal"><option value="general">一般</option><option value="account">アカウント</option><option value="privacy">個人情報・削除等</option><option value="bug">不具合</option></select></label>
    <label className="block text-sm font-bold">お名前 <span className="font-normal text-slate-400">（任意）</span><input value={name} onChange={(event) => { requestIdRef.current = null; setName(event.target.value); }} maxLength={80} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label>
    <label className="block text-sm font-bold">返信先メールアドレス <span className="text-rose-600">（必須）</span><input required type="email" value={email} onChange={(event) => { requestIdRef.current = null; setEmail(event.target.value); }} maxLength={254} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label>
    <label className="block text-sm font-bold">内容 <span className="text-rose-600">（必須）</span><textarea required value={message} onChange={(event) => { requestIdRef.current = null; setMessage(event.target.value); }} aria-invalid={messageTooLong} className="mt-2 min-h-40 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /><span className={`mt-1 block text-right text-xs font-normal ${messageTooLong ? "text-rose-700" : "text-slate-500"}`}>{message.length.toLocaleString()} / {SUPPORT_TEXT_LIMITS.reply.toLocaleString()}</span>{messageTooLong && <span className="mt-1 block text-xs font-normal text-rose-700" role="alert">内容が文字数上限を超えています。超過中の内容は保存されません。</span>}<span className="mt-1 block text-xs font-normal text-slate-500">パスワードやAPIキーは入力しないでください。</span></label>
    {status && <p role="status" className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-semibold">{status}</p>}
    {receiptId && <p className="break-all text-xs text-slate-500">受付ID: {receiptId}</p>}
    {threadUrl && <a className="inline-flex rounded-lg border border-cyan-700 px-4 py-2 text-sm font-black text-cyan-700" href={threadUrl}>このお問い合わせの会話を開く</a>}
    <button disabled={saving || !email.trim() || !message.trim() || messageTooLong} className="rounded-lg bg-cyan-700 px-5 py-3 font-black text-white disabled:opacity-40">{saving ? "送信中…" : "送信する"}</button>
  </form>;
}
