const baseGeneralWordGenres = [
  { key: "food_meals", name: "料理・食べ物" },
  { key: "sweets_desserts", name: "お菓子・デザート" },
  { key: "drinks", name: "飲み物" },
  { key: "ingredients_seasonings", name: "食材・調味料" },
  { key: "fruits_vegetables", name: "果物・野菜" },
  { key: "mammals", name: "哺乳類" },
  { key: "birds", name: "鳥" },
  { key: "aquatic_animals", name: "魚・水の生き物" },
  { key: "insects_small_animals", name: "昆虫・小さな生き物" },
  { key: "plants_flowers_trees", name: "植物・花・樹木" },
  { key: "home_rooms", name: "家・部屋" },
  { key: "furniture_interior", name: "家具・インテリア" },
  { key: "daily_goods", name: "生活用品" },
  { key: "kitchen_tools", name: "台所用品" },
  { key: "clothes_footwear", name: "服・履物" },
  { key: "accessories_belongings", name: "装飾品・持ち物" },
  { key: "stationery_office", name: "文房具・事務用品" },
  { key: "road_vehicles", name: "自動車・道路の乗り物" },
  { key: "rail_public_transport", name: "電車・公共交通" },
  { key: "ships_aircraft", name: "船・飛行機" },
  { key: "buildings_public_facilities", name: "建物・公共施設" },
  { key: "shops_commercial_facilities", name: "店・商業施設" },
  { key: "town_roads", name: "街・道路" },
  { key: "travel_tourism_lodging", name: "旅行・観光・宿泊" },
  { key: "terrain_geography", name: "地形・地理" },
  { key: "weather_meteorology", name: "天気・気象" },
  { key: "nature_environment", name: "自然・環境" },
  { key: "space_astronomy", name: "宇宙・天体" },
  { key: "body", name: "体・身体" },
  { key: "health_medical", name: "健康・病気・医療" },
  { key: "jobs_work", name: "仕事・職業" },
  { key: "school_study", name: "学校・勉強" },
  { key: "sports", name: "スポーツ" },
  { key: "outdoor_leisure", name: "アウトドア・レジャー" },
  { key: "toys_games", name: "おもちゃ・ゲーム" },
  { key: "music_instruments", name: "音楽・楽器" },
  { key: "film_theater_entertainment", name: "映画・演劇・芸能" },
  { key: "books_language_writing", name: "本・言葉・文章" },
  { key: "art_crafts", name: "美術・工芸" },
  { key: "science_experiments", name: "科学・実験" },
  { key: "computers_internet", name: "コンピューター・インターネット" },
  { key: "machines_appliances_electricity", name: "機械・家電・電気" },
  { key: "media_communications", name: "メディア・通信" },
  { key: "society_law_public_services", name: "社会・法律・公共サービス" },
  { key: "money_economy_shopping", name: "お金・経済・買い物" },
  { key: "history_culture_customs", name: "歴史・文化・風習" },
  { key: "family_relationships", name: "家族・人間関係" },
  { key: "emotion_personality_abstract", name: "感情・性格・抽象概念" },
  { key: "time_calendar_seasonal_events", name: "時間・暦・季節行事" },
  { key: "colors_shapes_materials_quantities", name: "色・形・素材・数量" },
  { key: "cooking_methods_techniques", name: "調理法・料理技術" },
  { key: "meat_seafood_dairy", name: "肉・魚介・乳製品" },
  { key: "pets_livestock", name: "ペット・家畜" },
  { key: "reptiles_amphibians", name: "爬虫類・両生類" },
  { key: "microorganisms_fungi", name: "微生物・菌類" },
  { key: "agriculture_forestry_fisheries", name: "農業・林業・漁業" },
  { key: "architecture_construction", name: "建築・建設" },
  { key: "tools_diy", name: "工具・DIY" },
  { key: "disasters_preparedness", name: "防災・災害" },
  { key: "geology_minerals", name: "地質・鉱物" },
  { key: "biology_ecology", name: "生物・生態" },
  { key: "chemistry_substances", name: "化学・物質" },
  { key: "physics_energy", name: "物理・エネルギー" },
  { key: "mathematics_statistics", name: "数学・統計" },
  { key: "psychology_cognition", name: "心理・認知" },
  { key: "politics_administration", name: "政治・行政" },
  { key: "management_finance", name: "経営・金融" },
  { key: "international_relations_diplomacy", name: "国際社会・外交" },
  { key: "religion_mythology", name: "宗教・神話" },
  { key: "philosophy_ethics", name: "哲学・倫理" },
  { key: "linguistics_grammar", name: "言語・文法" },
  { key: "publishing_journalism", name: "出版・報道" },
  { key: "welfare_caregiving", name: "福祉・介護" },
  { key: "crime_prevention_safety", name: "防犯・安全" },
  { key: "beauty_grooming", name: "美容・身だしなみ" },
] as const;

export const hardWordGenres = [
  { key: "hard_epistemology", name: "認識論・知識論" },
  { key: "hard_metaphysics", name: "形而上学・存在論" },
  { key: "hard_logic_argumentation", name: "論理学・論証" },
  { key: "hard_normative_ethics", name: "規範倫理学" },
  { key: "hard_aesthetics", name: "美学・芸術理論" },
  { key: "hard_political_theory", name: "政治思想・政治理論" },
  { key: "hard_jurisprudence", name: "法哲学・法理学" },
  { key: "hard_constitutional_law", name: "憲法学" },
  { key: "hard_civil_law", name: "民法学" },
  { key: "hard_criminal_law", name: "刑法学" },
  { key: "hard_microeconomics", name: "ミクロ経済学" },
  { key: "hard_macroeconomics", name: "マクロ経済学" },
  { key: "hard_accounting_finance", name: "会計学・金融論" },
  { key: "hard_sociology", name: "社会学・社会理論" },
  { key: "hard_anthropology", name: "文化人類学・民俗学" },
  { key: "hard_cognitive_psychology", name: "認知心理学" },
  { key: "hard_phonetics_phonology", name: "音声学・音韻論" },
  { key: "hard_syntax_semantics", name: "統語論・意味論" },
  { key: "hard_literary_theory", name: "文芸理論" },
  { key: "hard_historiography", name: "歴史学・史学史" },
  { key: "hard_archaeology", name: "考古学" },
  { key: "hard_religious_studies", name: "宗教学" },
  { key: "hard_abstract_algebra", name: "代数学" },
  { key: "hard_mathematical_analysis", name: "解析学" },
  { key: "hard_geometry_topology", name: "幾何学・位相数学" },
  { key: "hard_probability_statistics", name: "確率論・数理統計" },
  { key: "hard_algorithms_computation", name: "アルゴリズム・計算理論" },
  { key: "hard_information_theory", name: "情報理論・符号理論" },
  { key: "hard_classical_mechanics", name: "力学" },
  { key: "hard_electromagnetism", name: "電磁気学" },
  { key: "hard_quantum_relativity", name: "量子論・相対論" },
  { key: "hard_cosmology", name: "天文学・宇宙論" },
  { key: "hard_physical_chemistry", name: "物理化学" },
  { key: "hard_organic_chemistry", name: "有機化学" },
  { key: "hard_inorganic_chemistry", name: "無機化学" },
  { key: "hard_genetics_molecular_biology", name: "遺伝学・分子生物学" },
  { key: "hard_cell_biochemistry", name: "細胞生物学・生化学" },
  { key: "hard_evolution_ecology", name: "進化学・生態学" },
  { key: "hard_anatomy_physiology", name: "解剖学・生理学" },
  { key: "hard_pathology_diagnostics", name: "病理学・診断学" },
  { key: "hard_pharmacology_immunology", name: "薬理学・免疫学" },
  { key: "hard_geophysics", name: "地球物理学" },
  { key: "hard_mineralogy_petrology", name: "鉱物学・岩石学" },
  { key: "hard_meteorology_oceanography", name: "気象学・海洋学" },
  { key: "hard_mechanical_engineering", name: "機械工学" },
  { key: "hard_control_electronics", name: "制御工学・電子工学" },
  { key: "hard_civil_architectural_engineering", name: "土木工学・建築工学" },
  { key: "hard_environmental_science", name: "環境科学" },
  { key: "hard_agricultural_science", name: "農学・森林科学" },
  { key: "hard_media_communication_theory", name: "メディア論・コミュニケーション論" },
] as const;

export const generalWordGenres = [
  ...baseGeneralWordGenres,
  ...hardWordGenres,
] as const;

export type GeneralWordGenreKey = (typeof generalWordGenres)[number]["key"];

const generalWordGenreByKey = new Map(
  generalWordGenres.map((genre, index) => [genre.key, { ...genre, sortOrder: index + 1 }]),
);

export function getGeneralWordGenre(key: string) {
  return generalWordGenreByKey.get(key as GeneralWordGenreKey) ?? null;
}
