import type { TopicCandidate } from "@/lib/wordwolf-topic-types";

export const additionalProperNounNearPairTopics: TopicCandidate[] = [
  { villageWord: "明治大学", wolfWord: "立教大学", reason: "首都圏の有名私立大学だが、校風や街のイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "品川駅", wolfWord: "上野駅", reason: "東京の大きな駅だが、街の性格や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "横浜マリンタワー", wolfWord: "通天閣", reason: "街のシンボルになる展望施設だが、地域や雰囲気が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "伊勢神宮", wolfWord: "出雲大社", reason: "有名な神社だが、地域や信仰のイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "東大寺", wolfWord: "法隆寺", reason: "奈良の有名な寺院だが、建物や歴史の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "武田信玄", wolfWord: "上杉謙信", reason: "戦国時代の有名人物だが、拠点や人物像の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "和泉式部", wolfWord: "清少納言", reason: "平安文学で知られる人物だが、作品や作風の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "森鴎外", wolfWord: "島崎藤村", reason: "近代文学の有名作家だが、作品の雰囲気や時代の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "源氏物語", wolfWord: "枕草子", reason: "古典で有名な作品だが、物語と随筆で読み味が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "古墳時代", wolfWord: "飛鳥時代", reason: "日本史の時代区分だが、政治や文化の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "メンデル", wolfWord: "ダーウィン", reason: "生物分野で有名な人物だが、遺伝と進化で語られる文脈が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "野口英世", wolfWord: "北里柴三郎", reason: "医学・細菌学で有名な人物だが、研究対象や語られ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "英検", wolfWord: "TOEIC", reason: "英語力を測る試験だが、対象や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Windows", wolfWord: "macOS", reason: "有名なPC用OSだが、メーカーや操作感が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Slack", wolfWord: "Discord", reason: "コミュニケーションツールだが、仕事寄りかコミュニティ寄りかの印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "LINE", wolfWord: "Instagram", reason: "身近なスマホアプリだが、会話中心か投稿中心かが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Netflix", wolfWord: "Amazon Prime Video", reason: "動画配信サービスだが、作品の探し方やサービス全体の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "ピカチュウ", wolfWord: "イーブイ", reason: "ポケモンで有名なキャラクターだが、見た目や進化の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "カービィ", wolfWord: "ヨッシー", reason: "任天堂の有名キャラクターだが、作品世界やキャラクター性が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "ドラえもん", wolfWord: "アンパンマン", reason: "国民的キャラクターだが、作品世界や助け方の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "山手線", wolfWord: "大阪環状線", reason: "都市を環状に走る有名路線だが、地域や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "札幌市", wolfWord: "仙台市", reason: "地方の中心都市だが、気候や街のイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
];

export const additionalProperNounBalancedPairTopics: TopicCandidate[] = [
  { villageWord: "伊達政宗", wolfWord: "真田幸村", reason: "戦国時代の有名人物だが、地域や語られ方の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "源頼朝", wolfWord: "足利尊氏", reason: "幕府を開いた人物だが、時代や武士政権の性格が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "西郷隆盛", wolfWord: "坂本龍馬", reason: "幕末維新期の有名人物だが、立場や行動の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ペリー", wolfWord: "マッカーサー", reason: "日本史で学ぶ外国人だが、関わった時代と影響が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ナポレオン", wolfWord: "カエサル", reason: "世界史で有名な軍事・政治指導者だが、時代や国家の背景が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ガリレオ", wolfWord: "ニュートン", reason: "科学史で有名な人物だが、扱った現象や功績の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "エジソン", wolfWord: "ライト兄弟", reason: "発明で有名な人物だが、電気と飛行で分野が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "コペルニクス", wolfWord: "ダーウィン", reason: "科学史で有名な人物だが、宇宙観と生命観で分野が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "パスカル", wolfWord: "デカルト", reason: "数学・哲学で知られる人物だが、連想される分野や業績が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ユークリッド", wolfWord: "アルキメデス", reason: "古代科学で有名な人物だが、幾何学と力学で印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "平安時代", wolfWord: "江戸時代", reason: "日本史の時代区分だが、政治や文化の中心が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "江戸幕府", wolfWord: "明治政府", reason: "日本の政治体制だが、身分制中心か近代国家形成かが違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "松尾芭蕉", wolfWord: "与謝蕪村", reason: "俳句で有名な人物だが、作風や時代の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "平家物語", wolfWord: "徒然草", reason: "古典で学ぶ作品だが、軍記物と随筆で性格が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "北海道", wolfWord: "沖縄県", reason: "観光地として有名な地域だが、気候や文化の印象が大きく違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "札幌", wolfWord: "福岡", reason: "地方の大都市だが、地域性や食文化の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "大阪城", wolfWord: "姫路城", reason: "有名な城だが、歴史背景や建物の見られ方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "甲子園球場", wolfWord: "東京ドーム", reason: "野球で有名な球場だが、雰囲気や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ドラゴンクエスト", wolfWord: "ファイナルファンタジー", reason: "有名なRPGシリーズだが、世界観や遊び心地が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "スプラトゥーン", wolfWord: "フォートナイト", reason: "対戦ゲームとして有名だが、画面の印象や勝ち方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "iPad", wolfWord: "Surface", reason: "有名なタブレット端末だが、用途やメーカーの印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "名人戦", wolfWord: "王将戦", reason: "将棋のタイトル戦だが、制度や注目され方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "棋聖戦", wolfWord: "王位戦", reason: "将棋のタイトル戦だが、開催時期や番勝負の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "NHK", wolfWord: "日本テレビ", reason: "有名なテレビ局だが、公共放送と民放で立ち位置が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
];

export const additionalProperNounWidePairTopics: TopicCandidate[] = [
  { villageWord: "ローマ帝国", wolfWord: "モンゴル帝国", reason: "世界史で有名な大帝国だが、地域や拡大の仕方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "大航海時代", wolfWord: "ルネサンス", reason: "世界史で重要な時代の動きだが、海洋進出と文化復興で焦点が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "第一次世界大戦", wolfWord: "ベトナム戦争", reason: "世界史で有名な戦争だが、時代や国際関係の背景が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "冷戦", wolfWord: "キューバ危機", reason: "現代史で学ぶ国際対立だが、長期構造と具体的事件で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "アメリカ独立宣言", wolfWord: "フランス人権宣言", reason: "近代史で有名な宣言だが、背景となる革命や内容の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "国富論", wolfWord: "社会契約論", reason: "社会科で名前を聞く古典的な著作だが、経済思想と政治思想で焦点が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "国会", wolfWord: "最高裁判所", reason: "公民で学ぶ国家機関だが、立法と司法で役割が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "日本国憲法", wolfWord: "民法", reason: "法律として有名だが、国家の基本ルールと生活上の権利関係で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "世界恐慌", wolfWord: "リーマン・ショック", reason: "経済危機として有名な出来事だが、時代や金融の背景が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ニクソン・ショック", wolfWord: "プラザ合意", reason: "経済史で出る国際金融の出来事だが、起きた背景や影響が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "阪神・淡路大震災", wolfWord: "伊勢湾台風", reason: "日本の大きな自然災害名だが、災害の種類や時代が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ハッブル宇宙望遠鏡", wolfWord: "すばる望遠鏡", reason: "天文学で有名な観測施設だが、運用主体や観測の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "メンデレーエフ", wolfWord: "キュリー夫人", reason: "化学史で有名な人物だが、周期表と放射線研究で連想が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "平安京", wolfWord: "平城京", reason: "古代日本の都だが、時代や街のイメージが違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "シルクロード", wolfWord: "万里の長城", reason: "世界史・地理で有名な中国周辺の用語だが、交易路と防衛施設で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ナイル川", wolfWord: "アマゾン川", reason: "世界地理で有名な大河だが、地域や自然環境が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "インド洋", wolfWord: "北極海", reason: "世界地理で出る海域だが、気候や接する地域の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ノーベル賞", wolfWord: "アカデミー賞", reason: "世界的に有名な賞だが、学術・平和と映画で分野が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "アジア競技大会", wolfWord: "ラグビーワールドカップ", reason: "国や地域を代表するスポーツ大会だが、競技の幅や文化が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "WBC", wolfWord: "FIFAワールドカップ", reason: "国代表のスポーツ大会だが、野球とサッカーで文化が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ABEMA", wolfWord: "ニコニコ動画", reason: "ネット動画サービスとして知られるが、番組編成とコメント文化で体験が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "GitHub", wolfWord: "Stack Overflow", reason: "開発者が使う有名サービスだが、コード管理と質問回答で役割が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ChatGPT", wolfWord: "Perplexity", reason: "AIサービスとして知られるが、会話と検索補助で使われ方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "京都大学", wolfWord: "東京藝術大学", reason: "有名な大学だが、総合大学と芸術系大学で語られ方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
];

export function createHintTopicGroups(
  properNounNearPairTopics: readonly TopicCandidate[],
  properNounBalancedPairTopics: readonly TopicCandidate[],
  properNounWidePairTopics: readonly TopicCandidate[],
): Array<{
  aliases: readonly string[];
  candidates: readonly TopicCandidate[];
}> {
  return [
  {
    aliases: ["将棋", "shogi"],
    candidates: [
      { villageWord: "歩", wolfWord: "香車", reason: "将棋の駒だが、動き方と使い方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "桂馬", wolfWord: "銀将", reason: "将棋の駒だが、動き方や攻め方の印象が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "金将", wolfWord: "銀将", reason: "将棋の金駒だが、守りや攻めでの使われ方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "飛車", wolfWord: "角行", reason: "将棋の大駒だが、動き方と使われ方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "王将", wolfWord: "玉将", reason: "将棋の中心となる駒だが、呼び方や使われる場面の印象が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "居飛車", wolfWord: "振り飛車", reason: "将棋の戦型だが、飛車を置く場所と序盤の考え方が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "矢倉", wolfWord: "美濃囲い", reason: "将棋の囲いだが、形や相性のよい戦型が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "王手", wolfWord: "詰み", reason: "将棋の終盤で出る言葉だが、危機の段階と終了条件で違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "定跡", wolfWord: "手筋", reason: "将棋の上達で使う言葉だが、序盤の型と局面の技で違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "棋譜", wolfWord: "感想戦", reason: "対局後に関わる言葉だが、記録と振り返りで役割が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "詰将棋", wolfWord: "次の一手", reason: "将棋の問題形式だが、終盤の詰みと局面判断で違う", dictionarySource: "curated-pairs", pairDistance: "wide", sourceMode: "curated-pairs" },
      { villageWord: "持ち駒", wolfWord: "成駒", reason: "将棋の駒に関わる仕組みだが、手元の駒と成った駒で違う", dictionarySource: "curated-pairs", pairDistance: "wide", sourceMode: "curated-pairs" },
      { villageWord: "名人戦", wolfWord: "竜王戦", reason: "将棋の大きなタイトル戦だが、制度や序列の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "叡王戦", wolfWord: "棋王戦", reason: "将棋のタイトル戦だが、歴史や開催形式の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "羽生善治", wolfWord: "藤井聡太", reason: "将棋で非常に有名な棋士だが、活躍した時代や語られ方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "渡辺明", wolfWord: "佐藤天彦", reason: "将棋の有名棋士だが、棋風やタイトル歴の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "森内俊之", wolfWord: "谷川浩司", reason: "将棋の有名棋士だが、世代や語られ方の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
    ],
  },
  {
    aliases: ["歴史", "日本史", "世界史", "社会", "勉強", "学習", "受験", "テスト", "学校", "教科"],
    candidates: [
      ...properNounNearPairTopics.slice(-3),
      ...properNounBalancedPairTopics.slice(-4),
      ...properNounWidePairTopics.slice(-3),
      ...additionalProperNounNearPairTopics.filter((topic) => /時代|時|文学|物語|枕草子|メンデル|ダーウィン|野口英世|北里柴三郎|英検|TOEIC/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /史|時代|幕府|人物|科学|数学|俳句|古典|大学/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /世界史|公民|法律|経済|地学|宇宙|化学|地理|大学/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
    ],
  },
  {
    aliases: ["理科", "科学", "物理", "化学", "生物", "地学", "数学", "算数"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /フェルマー|ガウス/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounBalancedPairTopics.filter((topic) => /ファラデー|マクスウェル/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /メンデル|ダーウィン|野口英世|北里柴三郎/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /ガリレオ|ニュートン|エジソン|ライト兄弟|コペルニクス|ダーウィン|パスカル|デカルト|ユークリッド|アルキメデス/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /ハッブル宇宙望遠鏡|すばる望遠鏡|メンデレーエフ|キュリー夫人/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["ゲーム", "任天堂", "ポケモン", "マリオ", "RPG", "switch", "スイッチ"],
    candidates: [
      ...properNounWidePairTopics.filter((topic) => /Nintendo|PlayStation/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /ピカチュウ|イーブイ|カービィ|ヨッシー/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /ドラゴンクエスト|ファイナルファンタジー|スプラトゥーン|フォートナイト/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["IT", "アプリ", "SNS", "動画", "AI", "パソコン", "スマホ", "開発"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /ABEMA|TVer|iPhone|Pixel/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /Windows|macOS|Slack|Discord|LINE|Instagram|Netflix|Amazon Prime Video/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /ABEMA|ニコニコ動画|GitHub|Stack Overflow|ChatGPT|Perplexity/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["地理", "旅行", "観光", "都市", "駅", "鉄道", "路線"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /京都|奈良|横浜ランドマークタワー|あべのハルカス/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounBalancedPairTopics.filter((topic) => /箱根|日光|東京ディズニーランド|ユニバーサル/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounWidePairTopics.filter((topic) => /東海道新幹線|山手線/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /品川駅|上野駅|横浜マリンタワー|通天閣|山手線|大阪環状線|札幌市|仙台市/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /北海道|沖縄県|札幌|福岡|大阪城|姫路城/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /ナイル川|アマゾン川|インド洋|北極海|平安京|平城京/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  ];
}
