import type { TopicCandidate } from "@/lib/wordwolf-topic-types";

export const additionalProperNounNearPairTopics: TopicCandidate[] = [
  { villageWord: "早稲田大学", wolfWord: "慶應義塾大学", reason: "有名な私立大学だが、校風やイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "東京駅", wolfWord: "新宿駅", reason: "東京の代表的な駅だが、街の性格や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "東京タワー", wolfWord: "東京スカイツリー", reason: "東京の有名な電波塔だが、時代や眺めの印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "伊勢神宮", wolfWord: "出雲大社", reason: "有名な神社だが、地域や信仰のイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "東大寺", wolfWord: "法隆寺", reason: "奈良の有名な寺院だが、建物や歴史の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "織田信長", wolfWord: "豊臣秀吉", reason: "戦国時代の有名人物だが、出自や統一への関わり方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "紫式部", wolfWord: "清少納言", reason: "平安文学で有名な人物だが、作品や作風の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "夏目漱石", wolfWord: "芥川龍之介", reason: "近代文学の有名作家だが、作品の雰囲気や時代の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "源氏物語", wolfWord: "枕草子", reason: "古典で有名な作品だが、物語と随筆で読み味が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "古墳時代", wolfWord: "飛鳥時代", reason: "日本史の時代区分だが、政治や文化の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "DNA", wolfWord: "RNA", reason: "生物で学ぶ遺伝に関わる用語だが、役割や構造の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "光合成", wolfWord: "呼吸", reason: "生物で学ぶエネルギーに関わる働きだが、向きや場面が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "英検", wolfWord: "TOEIC", reason: "英語力を測る試験だが、対象や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Windows", wolfWord: "macOS", reason: "有名なPC用OSだが、メーカーや操作感が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Slack", wolfWord: "Discord", reason: "コミュニケーションツールだが、仕事寄りかコミュニティ寄りかの印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "LINE", wolfWord: "Instagram", reason: "身近なスマホアプリだが、会話中心か投稿中心かが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "Netflix", wolfWord: "Amazon Prime Video", reason: "動画配信サービスだが、作品の探し方やサービス全体の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "ピカチュウ", wolfWord: "イーブイ", reason: "ポケモンで有名なキャラクターだが、見た目や進化の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "マリオ", wolfWord: "ルイージ", reason: "任天堂の有名キャラクターだが、主役感やキャラクター性が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "ドラえもん", wolfWord: "アンパンマン", reason: "国民的キャラクターだが、作品世界や助け方の印象が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "山手線", wolfWord: "大阪環状線", reason: "都市を環状に走る有名路線だが、地域や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
  { villageWord: "札幌市", wolfWord: "仙台市", reason: "地方の中心都市だが、気候や街のイメージが違う", dictionarySource: "proper-noun", pairDistance: "near", sourceMode: "proper-noun" },
];

export const additionalProperNounBalancedPairTopics: TopicCandidate[] = [
  { villageWord: "徳川家康", wolfWord: "豊臣秀吉", reason: "天下統一に関わる有名人物だが、政権の作り方や人物像が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "源頼朝", wolfWord: "足利尊氏", reason: "幕府を開いた人物だが、時代や武士政権の性格が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "西郷隆盛", wolfWord: "坂本龍馬", reason: "幕末維新期の有名人物だが、立場や行動の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ペリー", wolfWord: "マッカーサー", reason: "日本史で学ぶ外国人だが、関わった時代と影響が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ナポレオン", wolfWord: "カエサル", reason: "世界史で有名な軍事・政治指導者だが、時代や国家の背景が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ガリレオ", wolfWord: "ニュートン", reason: "科学史で有名な人物だが、扱った現象や功績の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "エジソン", wolfWord: "ライト兄弟", reason: "発明で有名な人物だが、電気と飛行で分野が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "地動説", wolfWord: "進化論", reason: "科学史で有名な考え方だが、宇宙観と生命観で分野が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "確率", wolfWord: "統計", reason: "数学で関係する単元だが、予測とデータ整理で使い方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "方程式", wolfWord: "関数", reason: "数学でよく出る単元だが、未知数を解く考え方と対応関係を見る考え方で違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "平安時代", wolfWord: "江戸時代", reason: "日本史の時代区分だが、政治や文化の中心が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "江戸幕府", wolfWord: "明治政府", reason: "日本の政治体制だが、身分制中心か近代国家形成かが違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "松尾芭蕉", wolfWord: "与謝蕪村", reason: "俳句で有名な人物だが、作風や時代の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "平家物語", wolfWord: "徒然草", reason: "古典で学ぶ作品だが、軍記物と随筆で性格が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "北海道", wolfWord: "沖縄県", reason: "観光地として有名な地域だが、気候や文化の印象が大きく違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "札幌", wolfWord: "福岡", reason: "地方の大都市だが、地域性や食文化の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "大阪城", wolfWord: "姫路城", reason: "有名な城だが、歴史背景や建物の見られ方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "甲子園球場", wolfWord: "東京ドーム", reason: "野球で有名な球場だが、雰囲気や使われ方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "ドラゴンクエスト", wolfWord: "ファイナルファンタジー", reason: "有名なRPGシリーズだが、世界観や遊び心地が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "スプラトゥーン", wolfWord: "フォートナイト", reason: "対戦ゲームとして有名だが、画面の印象や勝ち方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "iPad", wolfWord: "Surface", reason: "有名なタブレット端末だが、用途やメーカーの印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "名人戦", wolfWord: "王将戦", reason: "将棋のタイトル戦だが、制度や注目され方が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "棋聖戦", wolfWord: "王位戦", reason: "将棋のタイトル戦だが、開催時期や番勝負の印象が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
  { villageWord: "NHK", wolfWord: "日本テレビ", reason: "有名なテレビ局だが、公共放送と民放で立ち位置が違う", dictionarySource: "proper-noun", pairDistance: "balanced", sourceMode: "proper-noun" },
];

export const additionalProperNounWidePairTopics: TopicCandidate[] = [
  { villageWord: "ローマ帝国", wolfWord: "モンゴル帝国", reason: "世界史で有名な大帝国だが、地域や拡大の仕方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "大航海時代", wolfWord: "ルネサンス", reason: "世界史で重要な時代の動きだが、海洋進出と文化復興で焦点が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "第一次世界大戦", wolfWord: "第二次世界大戦", reason: "世界史で有名な大戦だが、原因や戦後体制の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "冷戦", wolfWord: "キューバ危機", reason: "現代史で学ぶ国際対立だが、長期構造と具体的事件で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "アメリカ独立宣言", wolfWord: "フランス人権宣言", reason: "近代史で有名な宣言だが、背景となる革命や内容の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "資本主義", wolfWord: "社会主義", reason: "社会科で学ぶ経済・政治の考え方だが、重視する仕組みが違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "国会", wolfWord: "最高裁判所", reason: "公民で学ぶ国家機関だが、立法と司法で役割が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "日本国憲法", wolfWord: "民法", reason: "法律として有名だが、国家の基本ルールと生活上の権利関係で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "需要", wolfWord: "供給", reason: "経済で対になる考え方だが、買う側と売る側で視点が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "インフレ", wolfWord: "デフレ", reason: "経済で学ぶ物価の動きだが、上昇と下落で社会への影響が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "プレートテクトニクス", wolfWord: "火山活動", reason: "地学で学ぶ現象だが、地球の大きな仕組みと具体的な活動で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "太陽系", wolfWord: "銀河系", reason: "宇宙で学ぶまとまりだが、スケールが大きく違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "元素周期表", wolfWord: "化学反応式", reason: "化学でよく見るものだが、元素の整理と反応の表現で役割が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "平安京", wolfWord: "平城京", reason: "古代日本の都だが、時代や街のイメージが違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "シルクロード", wolfWord: "万里の長城", reason: "世界史・地理で有名な中国周辺の用語だが、交易路と防衛施設で違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ナイル川", wolfWord: "アマゾン川", reason: "世界地理で有名な大河だが、地域や自然環境が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "太平洋", wolfWord: "大西洋", reason: "世界の大洋だが、接する地域や歴史上のイメージが違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ノーベル賞", wolfWord: "アカデミー賞", reason: "世界的に有名な賞だが、学術・平和と映画で分野が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "オリンピック", wolfWord: "FIFAワールドカップ", reason: "世界的なスポーツ大会だが、競技数や盛り上がり方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "WBC", wolfWord: "FIFAワールドカップ", reason: "国代表のスポーツ大会だが、野球とサッカーで文化が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "YouTube", wolfWord: "ニコニコ動画", reason: "動画サービスとして有名だが、文化やコメント体験が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "GitHub", wolfWord: "Stack Overflow", reason: "開発者が使う有名サービスだが、コード管理と質問回答で役割が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "ChatGPT", wolfWord: "Gemini", reason: "有名なAIサービスだが、提供元や使われ方の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
  { villageWord: "京都大学", wolfWord: "東京大学", reason: "有名な国立大学だが、地域や校風のイメージが違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
];

export function createHintTopicGroups(
  properNounNearPairTopics: readonly TopicCandidate[],
  properNounBalancedPairTopics: readonly TopicCandidate[],
  properNounWidePairTopics: readonly TopicCandidate[],
): Array<{
  aliases: readonly string[];
  candidates: readonly TopicCandidate[];
}> {
  return [
  {
    aliases: ["将棋", "shogi"],
    candidates: [
      { villageWord: "歩", wolfWord: "香車", reason: "将棋の駒だが、動き方と使い方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "桂馬", wolfWord: "銀将", reason: "将棋の駒だが、動き方や攻め方の印象が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "金将", wolfWord: "銀将", reason: "将棋の金駒だが、守りや攻めでの使われ方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "飛車", wolfWord: "角行", reason: "将棋の大駒だが、動き方と使われ方が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "王将", wolfWord: "玉将", reason: "将棋の中心となる駒だが、呼び方や使われる場面の印象が違う", dictionarySource: "curated-pairs", pairDistance: "near", sourceMode: "curated-pairs" },
      { villageWord: "居飛車", wolfWord: "振り飛車", reason: "将棋の戦型だが、飛車を置く場所と序盤の考え方が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "矢倉", wolfWord: "美濃囲い", reason: "将棋の囲いだが、形や相性のよい戦型が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "王手", wolfWord: "詰み", reason: "将棋の終盤で出る言葉だが、危機の段階と終了条件で違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "定跡", wolfWord: "手筋", reason: "将棋の上達で使う言葉だが、序盤の型と局面の技で違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "棋譜", wolfWord: "感想戦", reason: "対局後に関わる言葉だが、記録と振り返りで役割が違う", dictionarySource: "curated-pairs", pairDistance: "balanced", sourceMode: "curated-pairs" },
      { villageWord: "詰将棋", wolfWord: "次の一手", reason: "将棋の問題形式だが、終盤の詰みと局面判断で違う", dictionarySource: "curated-pairs", pairDistance: "wide", sourceMode: "curated-pairs" },
      { villageWord: "持ち駒", wolfWord: "成駒", reason: "将棋の駒に関わる仕組みだが、手元の駒と成った駒で違う", dictionarySource: "curated-pairs", pairDistance: "wide", sourceMode: "curated-pairs" },
      { villageWord: "名人戦", wolfWord: "竜王戦", reason: "将棋の大きなタイトル戦だが、制度や序列の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "叡王戦", wolfWord: "棋王戦", reason: "将棋のタイトル戦だが、歴史や開催形式の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "羽生善治", wolfWord: "藤井聡太", reason: "将棋で非常に有名な棋士だが、活躍した時代や語られ方が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "渡辺明", wolfWord: "佐藤天彦", reason: "将棋の有名棋士だが、棋風やタイトル歴の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
      { villageWord: "森内俊之", wolfWord: "谷川浩司", reason: "将棋の有名棋士だが、世代や語られ方の印象が違う", dictionarySource: "proper-noun", pairDistance: "wide", sourceMode: "proper-noun" },
    ],
  },
  {
    aliases: ["歴史", "日本史", "世界史", "社会", "勉強", "学習", "受験", "テスト", "学校", "教科"],
    candidates: [
      ...properNounNearPairTopics.slice(-3),
      ...properNounBalancedPairTopics.slice(-4),
      ...properNounWidePairTopics.slice(-3),
      ...additionalProperNounNearPairTopics.filter((topic) => /時代|時|文学|物語|枕草子|DNA|RNA|光合成|呼吸|英検|TOEIC/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /史|時代|幕府|人物|科学|数学|俳句|古典|大学/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /世界史|公民|法律|経済|地学|宇宙|化学|地理|大学/.test(`${topic.villageWord}${topic.wolfWord}${topic.reason}`)),
    ],
  },
  {
    aliases: ["理科", "科学", "物理", "化学", "生物", "地学", "数学", "算数"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /微分|積分/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounBalancedPairTopics.filter((topic) => /万有引力|相対性理論/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /DNA|RNA|光合成|呼吸/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /ガリレオ|ニュートン|エジソン|ライト兄弟|地動説|進化論|確率|統計|方程式|関数/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /プレートテクトニクス|火山活動|太陽系|銀河系|元素周期表|化学反応式/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["ゲーム", "任天堂", "ポケモン", "マリオ", "RPG", "switch", "スイッチ"],
    candidates: [
      ...properNounWidePairTopics.filter((topic) => /Nintendo|PlayStation/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /ピカチュウ|イーブイ|マリオ|ルイージ/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /ドラゴンクエスト|ファイナルファンタジー|スプラトゥーン|フォートナイト/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["IT", "アプリ", "SNS", "動画", "AI", "パソコン", "スマホ", "開発"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /YouTube|TikTok|iPhone|Pixel/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /Windows|macOS|Slack|Discord|LINE|Instagram|Netflix|Amazon Prime Video/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /YouTube|ニコニコ動画|GitHub|Stack Overflow|ChatGPT|Gemini/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  {
    aliases: ["地理", "旅行", "観光", "都市", "駅", "鉄道", "路線"],
    candidates: [
      ...properNounNearPairTopics.filter((topic) => /京都|奈良|横浜ランドマークタワー|あべのハルカス/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounBalancedPairTopics.filter((topic) => /箱根|日光|東京ディズニーランド|ユニバーサル/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...properNounWidePairTopics.filter((topic) => /東海道新幹線|山手線/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounNearPairTopics.filter((topic) => /東京駅|新宿駅|東京タワー|東京スカイツリー|山手線|大阪環状線|札幌市|仙台市/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounBalancedPairTopics.filter((topic) => /北海道|沖縄県|札幌|福岡|大阪城|姫路城/.test(`${topic.villageWord}${topic.wolfWord}`)),
      ...additionalProperNounWidePairTopics.filter((topic) => /ナイル川|アマゾン川|太平洋|大西洋|平安京|平城京/.test(`${topic.villageWord}${topic.wolfWord}`)),
    ],
  },
  ];
}
