import Link from "next/link";

export type LobbyAuthMode = "login" | "register";
type Props = { name: string; password: string; email: string; resetEmail: string; authMode: LobbyAuthMode; isLoggedIn: boolean; legalAccepted: boolean; showPasswordReset: boolean; isSaving: boolean; isRequestingReset: boolean; message: string; onNameChange: (v: string) => void; onPasswordChange: (v: string) => void; onEmailChange: (v: string) => void; onResetEmailChange: (v: string) => void; onAuthModeChange: (v: LobbyAuthMode) => void; onLegalAcceptedChange: (v: boolean) => void; onPasswordResetVisibilityChange: (v: boolean) => void; onClearMessage: () => void; onSubmit: () => void; onRequestReset: () => void; onLogout: () => void };
const inputClass = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 outline-none transition focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/20";

export function LobbyAccountPanel(props: Props) {
  return <div className="rounded-lg border border-white/10 bg-white/[0.96] p-4 shadow-[0_18px_50px_rgba(15,23,42,0.18)]">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-cyan-700">Account</p><h2 className="text-lg font-bold text-slate-950">プレイヤーアカウント</h2></div>{props.isLoggedIn && <button type="button" onClick={props.onLogout} className="rounded-md border border-slate-300 bg-white px-2 py-1 text-xs font-semibold text-slate-600 transition hover:bg-slate-50">ログアウト</button>}</div>
    {!props.isLoggedIn && <div className="mt-4 grid grid-cols-2 gap-2 rounded-lg bg-slate-100 p-1">{([['login','ログイン'],['register','新規作成']] as const).map(([mode,label]) => <button key={mode} type="button" onClick={() => { props.onAuthModeChange(mode); props.onClearMessage(); }} className={`rounded-md px-3 py-2 text-sm font-semibold transition ${props.authMode === mode ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-800"}`}>{label}</button>)}</div>}
    <label className="mt-4 block text-sm font-medium text-slate-700">プレイヤー名<input value={props.name} onChange={(e) => props.onNameChange(e.target.value)} disabled={props.isLoggedIn} className={`${inputClass} disabled:bg-slate-100`} placeholder="例: yusuke" /></label>
    {!props.isLoggedIn && <label className="mt-3 block text-sm font-medium text-slate-700">パスワード<input value={props.password} onChange={(e) => props.onPasswordChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") props.onSubmit(); }} type="password" autoComplete={props.authMode === "register" ? "new-password" : "current-password"} className={inputClass} placeholder="4文字以上" /></label>}
    {!props.isLoggedIn && props.authMode === "register" && <><label className="mt-3 block text-sm font-medium text-slate-700">メールアドレス <span className="font-normal text-slate-400">（任意）</span><input value={props.email} onChange={(e) => props.onEmailChange(e.target.value)} type="email" autoComplete="email" className={inputClass} placeholder="you@example.com" /><span className="mt-1 block text-xs font-normal leading-5 text-slate-500">登録しておくと、パスワードを忘れた場合にメールから再設定できます。</span></label><label className="mt-3 flex cursor-pointer items-start gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs leading-5 text-slate-700"><input type="checkbox" checked={props.legalAccepted} onChange={(e) => props.onLegalAcceptedChange(e.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-cyan-600" /><span><Link href="/terms" target="_blank" className="font-bold text-cyan-700 underline">利用規約</Link>と<Link href="/privacy" target="_blank" className="font-bold text-cyan-700 underline">プライバシーポリシー</Link>を確認し、同意します。</span></label></>}
    {!props.isLoggedIn && <button type="button" onClick={props.onSubmit} disabled={props.isSaving || (props.authMode === "register" && !props.legalAccepted)} className="mt-4 w-full rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-cyan-500 disabled:bg-slate-300">{props.isSaving ? "確認中..." : props.authMode === "register" ? "アカウント作成" : "ログイン"}</button>}
    {!props.isLoggedIn && props.authMode === "login" && !props.showPasswordReset && <button type="button" onClick={() => { props.onPasswordResetVisibilityChange(true); props.onClearMessage(); }} className="mt-3 w-full text-center text-sm font-semibold text-cyan-700 underline-offset-4 hover:underline">パスワードを忘れた方</button>}
    {!props.isLoggedIn && props.authMode === "login" && props.showPasswordReset && <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-sm font-bold text-slate-800">パスワードを再設定</p><p className="mt-1 text-xs leading-5 text-slate-500">登録したメールアドレスへ、1時間有効な再設定リンクを送ります。</p><input value={props.resetEmail} onChange={(e) => props.onResetEmailChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") props.onRequestReset(); }} type="email" autoComplete="email" className={`mt-3 ${inputClass}`} placeholder="登録したメールアドレス" /><div className="mt-2 flex gap-2"><button type="button" onClick={props.onRequestReset} disabled={props.isRequestingReset || !props.resetEmail.trim()} className="flex-1 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white transition hover:bg-cyan-500 disabled:bg-slate-300">{props.isRequestingReset ? "送信中..." : "再設定メールを送る"}</button><button type="button" onClick={() => props.onPasswordResetVisibilityChange(false)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-600">閉じる</button></div></div>}
    {props.message && <p className="mt-3 rounded-lg border border-cyan-100 bg-cyan-50 px-3 py-2 text-sm font-semibold text-cyan-800">{props.message}</p>}
  </div>;
}
