"use client";

import Link from "next/link";
import { useAppLocale } from "@/app/components/AppLocaleProvider";

export type LobbyAuthMode = "login" | "register";
type Props = { name: string; password: string; email: string; resetEmail: string; authMode: LobbyAuthMode; isLoggedIn: boolean; legalAccepted: boolean; showPasswordReset: boolean; isSaving: boolean; isRequestingReset: boolean; message: string; onNameChange: (v: string) => void; onPasswordChange: (v: string) => void; onEmailChange: (v: string) => void; onResetEmailChange: (v: string) => void; onAuthModeChange: (v: LobbyAuthMode) => void; onLegalAcceptedChange: (v: boolean) => void; onPasswordResetVisibilityChange: (v: boolean) => void; onClearMessage: () => void; onSubmit: () => void; onRequestReset: () => void; onLogout: () => void };
const inputClass = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 outline-none transition focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/20";

export function LobbyAccountPanel(props: Props) {
  const { t } = useAppLocale();
  return <div className="rounded-lg border border-white/10 bg-white/[0.96] p-4 shadow-[0_18px_50px_rgba(15,23,42,0.18)]">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-cyan-700">Account</p><h2 className="text-lg font-bold text-slate-950">{t("account.account")}</h2></div>{props.isLoggedIn && <button type="button" onClick={props.onLogout} className="rounded-md border border-slate-300 bg-white px-2 py-1 text-xs font-semibold text-slate-600 transition hover:bg-slate-50">{t("account.logout")}</button>}</div>
    {!props.isLoggedIn && <div className="mt-4 grid grid-cols-2 gap-2 rounded-lg bg-slate-100 p-1">{([['login',t("account.login")],['register',t("account.register")]] as const).map(([mode,label]) => <button key={mode} type="button" onClick={() => { props.onAuthModeChange(mode); props.onClearMessage(); }} className={`rounded-md px-3 py-2 text-sm font-semibold transition ${props.authMode === mode ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-800"}`}>{label}</button>)}</div>}
    <label className="mt-4 block text-sm font-medium text-slate-700">{t("account.playerName")}<input value={props.name} onChange={(e) => props.onNameChange(e.target.value)} disabled={props.isLoggedIn} className={`${inputClass} disabled:bg-slate-100`} placeholder="e.g. michel" /></label>
    {!props.isLoggedIn && <label className="mt-3 block text-sm font-medium text-slate-700">{t("account.password")}<input value={props.password} onChange={(e) => props.onPasswordChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") props.onSubmit(); }} type="password" autoComplete={props.authMode === "register" ? "new-password" : "current-password"} className={inputClass} placeholder={t("account.passwordHint")} /></label>}
    {!props.isLoggedIn && props.authMode === "register" && <><label className="mt-3 block text-sm font-medium text-slate-700">{t("account.email")} <span className="font-normal text-slate-400">{t("account.optional")}</span><input value={props.email} onChange={(e) => props.onEmailChange(e.target.value)} type="email" autoComplete="email" className={inputClass} placeholder="you@example.com" /><span className="mt-1 block text-xs font-normal leading-5 text-slate-500">{t("account.emailHelp")}</span></label><label className="mt-3 flex cursor-pointer items-start gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs leading-5 text-slate-700"><input type="checkbox" checked={props.legalAccepted} onChange={(e) => props.onLegalAcceptedChange(e.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-cyan-600" /><span>{t("account.legalConsentBefore")}<Link href="/terms" target="_blank" className="font-bold text-cyan-700 underline">{t("footer.terms")}</Link>{t("account.legalConsentMiddle")}<Link href="/privacy" target="_blank" className="font-bold text-cyan-700 underline">{t("footer.privacy")}</Link>{t("account.legalConsentAfter")}</span></label></>}
    {!props.isLoggedIn && <button type="button" onClick={props.onSubmit} disabled={props.isSaving || (props.authMode === "register" && !props.legalAccepted)} className="mt-4 w-full rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-cyan-500 disabled:bg-slate-300">{props.isSaving ? t("account.checking") : props.authMode === "register" ? t("account.create") : t("account.login")}</button>}
    {!props.isLoggedIn && props.authMode === "login" && !props.showPasswordReset && <button type="button" onClick={() => { props.onPasswordResetVisibilityChange(true); props.onClearMessage(); }} className="mt-3 w-full text-center text-sm font-semibold text-cyan-700 underline-offset-4 hover:underline">{t("account.forgotPassword")}</button>}
    {!props.isLoggedIn && props.authMode === "login" && props.showPasswordReset && <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-sm font-bold text-slate-800">{t("account.resetPassword")}</p><p className="mt-1 text-xs leading-5 text-slate-500">{t("account.resetHelp")}</p><input value={props.resetEmail} onChange={(e) => props.onResetEmailChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") props.onRequestReset(); }} type="email" autoComplete="email" className={`mt-3 ${inputClass}`} placeholder={t("account.registeredEmail")} /><div className="mt-2 flex gap-2"><button type="button" onClick={props.onRequestReset} disabled={props.isRequestingReset || !props.resetEmail.trim()} className="flex-1 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white transition hover:bg-cyan-500 disabled:bg-slate-300">{props.isRequestingReset ? t("account.sending") : t("account.sendReset")}</button><button type="button" onClick={() => props.onPasswordResetVisibilityChange(false)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-600">{t("site.close")}</button></div></div>}
    {props.message && <p className="mt-3 rounded-lg border border-cyan-100 bg-cyan-50 px-3 py-2 text-sm font-semibold text-cyan-800">{props.message}</p>}
  </div>;
}
