"use client";

import type { DragEvent } from "react";
import { useAppLocale } from "@/app/components/AppLocaleProvider";
import { avatarColorOptions, defaultAvatarImage, defaultAvatarImages } from "@/lib/player-session";

type Props = { name: string; color: string; image: string | null; isLoggedIn: boolean; isSaving: boolean; isDragging: boolean; onColorChange: (color: string) => void; onImageChange: (image: string) => void; onFile: (file?: File) => void; onDrop: (event: DragEvent<HTMLElement>) => void; onDraggingChange: (dragging: boolean) => void; onOpenMyPage: () => void; onOpenInfo: () => void };

export function LobbyAccountMenu(props: Props) {
  const { t } = useAppLocale();
  const avatar = <span className="h-8 w-8 rounded-full border border-white/60 bg-cover bg-center" style={{ backgroundColor: props.color, backgroundImage: `url(${props.image || defaultAvatarImage})` }} aria-hidden="true" />;
  if (!props.isLoggedIn) return <div className="flex items-center gap-2 rounded-lg border border-white/15 bg-white/10 px-3 py-2">{avatar}<span className="max-w-[160px] truncate text-sm font-semibold text-cyan-50">{t("account.loggedOut")}</span></div>;
  return <details className="group relative"><summary aria-label={t("account.openMenu", { name: props.name })} className="flex cursor-pointer list-none items-center gap-2 rounded-lg border border-white/15 bg-white/10 px-3 py-2 transition hover:border-cyan-200/60 hover:bg-white/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300 [&::-webkit-details-marker]:hidden">{avatar}<span className="max-w-[160px] truncate text-sm font-semibold text-cyan-50">{props.name}</span><span className="text-xs text-slate-300 transition group-open:rotate-180" aria-hidden="true">▼</span></summary>
    <div className="absolute right-0 z-30 mt-2 w-72 rounded-lg border border-slate-200 bg-white p-3 text-slate-900 shadow-xl"><p className="truncate px-2 py-1 text-xs font-semibold text-slate-500">{t("account.loggedInAs", { name: props.name })}</p>
      <div className="mt-2 border-t border-slate-200 pt-3"><p className="text-xs font-bold text-slate-700">{t("account.avatarColor")}</p><div className="mt-2 grid grid-cols-8 gap-1.5">{avatarColorOptions.map((color) => <button key={color} type="button" aria-label={`${t("account.avatarColor")} ${color}`} aria-pressed={props.color === color} disabled={props.isSaving} onClick={() => props.onColorChange(color)} className={`h-7 w-7 rounded-full border-2 transition disabled:opacity-50 ${props.color === color ? "border-slate-900 ring-2 ring-cyan-300" : "border-white"}`} style={{ backgroundColor: color }} />)}</div></div>
      <div className="mt-3"><p className="text-xs font-bold text-slate-700">{t("account.avatarImage")}</p><div className="mt-2 grid grid-cols-5 gap-2">{defaultAvatarImages.map((image, index) => <button key={image} type="button" aria-label={`${t("account.avatarImage")} ${index + 1}`} aria-pressed={props.image === image} disabled={props.isSaving} onClick={() => props.onImageChange(image)} className={`h-10 w-10 rounded-full border-2 bg-cover bg-center transition disabled:opacity-50 ${props.image === image ? "border-cyan-500 ring-2 ring-cyan-200" : "border-slate-200"}`} style={{ backgroundColor: props.color, backgroundImage: `url(${image})` }} />)}</div>
        <label onDragEnter={(event) => { event.preventDefault(); if (!props.isSaving && event.dataTransfer.types.includes("Files")) props.onDraggingChange(true); }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "copy"; if (!props.isSaving && event.dataTransfer.types.includes("Files")) props.onDraggingChange(true); }} onDragLeave={(event) => { event.preventDefault(); props.onDraggingChange(false); }} onDrop={props.onDrop} className={`mt-2 flex cursor-pointer items-center justify-center rounded-md border px-3 py-2 text-center text-xs font-bold transition ${props.isDragging ? "border-cyan-500 bg-cyan-100 text-cyan-900 ring-2 ring-cyan-200" : "border-slate-300 bg-white text-slate-700 hover:bg-slate-50"}`}>{props.isDragging ? t("account.dropImage") : t("account.chooseImage")}<input type="file" accept="image/*" disabled={props.isSaving} onChange={(event) => { props.onFile(event.target.files?.[0]); event.currentTarget.value = ""; }} className="sr-only" /></label>
      </div>
      <button type="button" onClick={props.onOpenMyPage} className="mt-3 flex w-full items-center justify-center rounded-md bg-cyan-600 px-3 py-2 text-sm font-bold text-white transition hover:bg-cyan-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500/40">{t("account.openMyPage")}</button><button type="button" onClick={props.onOpenInfo} className="mt-2 flex w-full items-center justify-center rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-700 transition hover:bg-slate-50 lg:hidden">{t("account.openStats")}</button>
    </div>
  </details>;
}
