import { useState, type Dispatch, type SetStateAction } from "react";
import { currentPrivacyVersion, currentTermsVersion } from "@/lib/legal";
import type { PlayerSession } from "@/lib/player-session";
import type { LobbyAuthMode } from "./LobbyAccountPanel";

const errors: Record<string, string> = { INVALID_JSON: "入力内容を読み取れませんでした。", TERMS_REQUIRED: "利用規約とプライバシーポリシーへの同意が必要です。", STORE_NOT_CONFIGURED: "プレイヤー保存用ストレージが未設定です。", NAME_REQUIRED: "プレイヤー名を入力してください。", PASSWORD_INVALID: "パスワードは4文字以上128文字以内で入力してください。", ALREADY_EXISTS: "そのプレイヤー名はすでに使われています。", EMAIL_INVALID: "メールアドレスの形式を確認してください。", EMAIL_ALREADY_EXISTS: "そのメールアドレスは別のアカウントで使われています。", INVALID_CREDENTIALS: "プレイヤー名またはパスワードが違います。", UNKNOWN: "アカウント処理に失敗しました。", AUTH_NOT_CONFIGURED: "ログイン認証用のサーバー設定が未完了です。" };
const authMessage = (code: unknown) => typeof code === "string" ? errors[code] ?? errors.UNKNOWN : errors.UNKNOWN;
type Setter = Dispatch<SetStateAction<string>>;
type Params = { name: string; password: string; email: string; resetEmail: string; authMode: LobbyAuthMode; legalAccepted: boolean; avatarColor: string; avatarImage: string | null; applySession: (session: PlayerSession) => void; setMessage: Setter; setPassword: Setter; setEmail: Setter; setResetEmail: Setter; setShowPasswordReset: Dispatch<SetStateAction<boolean>> };

export function useLobbyAuthActions(params: Params) {
  const [isSaving, setIsSaving] = useState(false); const [isRequestingReset, setIsRequestingReset] = useState(false);
  const submitAccount = async () => { setIsSaving(true); params.setMessage(""); try { const response = await fetch("/api/player-account", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: params.authMode, name: params.name.trim(), password: params.password, email: params.authMode === "register" ? params.email : undefined, avatarColor: params.avatarColor, avatarImage: params.avatarImage, acceptedTerms: params.authMode === "register" ? params.legalAccepted : undefined, termsVersion: params.authMode === "register" ? currentTermsVersion : undefined, privacyVersion: params.authMode === "register" ? currentPrivacyVersion : undefined }) }); const data = await response.json() as { session?: PlayerSession; error?: string }; if (!response.ok || !data.session) return params.setMessage(authMessage(data.error)); params.applySession(data.session); params.setPassword(""); params.setEmail(""); params.setMessage(params.authMode === "register" ? "アカウントを作成してログインしました。" : "ログインしました。"); } catch { params.setMessage("通信に失敗しました。もう一度試してください。"); } finally { setIsSaving(false); } };
  const requestPasswordReset = async () => { setIsRequestingReset(true); params.setMessage(""); try { const response = await fetch("/api/player-password-reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "request", email: params.resetEmail }) }); const data = await response.json() as { error?: string }; if (!response.ok) return params.setMessage(data.error === "EMAIL_NOT_CONFIGURED" ? "メール送信機能がまだ設定されていません。管理者に連絡してください。" : "再設定メールの送信処理に失敗しました。時間をおいて再度お試しください。"); params.setMessage("登録済みのメールアドレスであれば、再設定用メールを送信しました。"); params.setShowPasswordReset(false); params.setResetEmail(""); } catch { params.setMessage("通信に失敗しました。もう一度試してください。"); } finally { setIsRequestingReset(false); } };
  return { isSaving, isRequestingReset, submitAccount, requestPasswordReset };
}
