import { useMemo } from "react";
import { defaultAvatarImage } from "@/lib/player-session";
import { reducedPlayerTimeLimitSeconds } from "@/lib/player-timeout-policy";
import type { Room } from "@/lib/wordwolf-game-types";
import { getClueParticipants, getClueSubmittedCount, getNextSimultaneousCluePlayer, getNextVotePlayer, getVoteCandidates, getVoteVoters, hasPostedClueThisRound } from "./game-flow";
import { maxWolfCount, normalizeStoredWolfCount, normalizeWolfIds } from "./wordwolf-room-adapter";
import { useWordWolfPhaseClock } from "./use-wordwolf-phase-clock";

export function useWordWolfViewModel(room: Room | null, activePlayerId: string, playerName: string, avatarColor: string, avatarImage: string | null) {
  const activePlayer = useMemo(() => room?.players.find((player) => player.id === activePlayerId) ?? null, [activePlayerId, room]);
  const currentPlayer = room?.players[room.currentTurnIndex] ?? null;
  const simultaneousNextCluePlayer = room?.phase === "clue" && room.clueMode === "simultaneous" ? getNextSimultaneousCluePlayer(room) : null;
  const wolfIds = room ? normalizeWolfIds(room) : [];
  const wolfPlayers = room?.players.filter((player) => wolfIds.includes(player.id)) ?? [];
  const wolfPlayer = wolfPlayers[0] ?? null;
  const accusedPlayer = room?.players.find((player) => player.id === room.accusedId) ?? null;
  const accusedIsWolf = Boolean(room?.accusedId && wolfIds.includes(room.accusedId));
  const finalAnswerPlayer = accusedIsWolf ? accusedPlayer : wolfPlayer;
  const nextVotePlayer = room ? getNextVotePlayer(room) : null;
  const isDebugMode = Boolean(room?.debugMode);
  const clueActor = room?.clueMode === "simultaneous" ? (isDebugMode ? simultaneousNextCluePlayer : activePlayer && room.phase === "clue" && getClueParticipants(room).some((player) => player.id === activePlayer.id) && !hasPostedClueThisRound(room, activePlayer.id) ? activePlayer : null) : isDebugMode ? currentPlayer : activePlayer;
  const voteActor = room?.phase === "vote" ? (isDebugMode ? nextVotePlayer : activePlayer && getVoteVoters(room).some((player) => player.id === activePlayer.id) && !room.votes[activePlayer.id] ? activePlayer : null) : null;
  const voteDisplayPlayer = isDebugMode ? voteActor : activePlayer;
  const guessActor = isDebugMode ? finalAnswerPlayer : activePlayer;
  const isHost = Boolean(room && activePlayerId === room.hostId);
  const headerName = activePlayer?.name || playerName.trim() || "ゲスト";
  const headerAvatarColor = activePlayer?.avatarColor || avatarColor;
  const headerAvatarImage = activePlayer?.avatarImage || avatarImage || defaultAvatarImage;
  const displayWordPlayer = isDebugMode && room?.phase === "clue" ? clueActor : activePlayer;
  const ownWord = displayWordPlayer && room && room.phase !== "lobby" ? wolfIds.includes(displayWordPlayer.id) ? room.wolfWord : room.villageWord : "";
  const resultTitle = room?.winner === "players" ? "結果" : room?.winner === "village" ? "村側の勝利" : "狼の勝利";
  const topicSourceLabel = room?.topicSource === "llm" ? room.topicDictionarySource === "proper-noun" ? "固有名詞" : "一般単語" : room?.topicSource === "fallback" ? room.topicFallbackExhausted ? "代替辞書（候補枯渇）" : "代替辞書" : "未取得";
  const voteVoters = room ? getVoteVoters(room) : [];
  const votedCount = room ? voteVoters.filter((player) => room.votes[player.id]).length : 0;
  const selectedVoteTargetId = room && voteDisplayPlayer ? room.votes[voteDisplayPlayer.id] : undefined;
  const clueParticipants = room ? getClueParticipants(room) : [];
  const clueSubmittedCount = room?.phase === "clue" ? getClueSubmittedCount(room) : 0;
  const canSubmitClue = Boolean(clueActor) && (room?.clueMode === "simultaneous" || clueActor?.id === currentPlayer?.id);
  const voteCandidates = room ? getVoteCandidates(room) : [];
  const allowedWolfCount = room ? maxWolfCount(room.players.length) : 1;
  const wolfCountOptions = room ? Array.from(new Set([...Array.from({ length: allowedWolfCount }, (_, index) => index + 1), normalizeStoredWolfCount(room.wolfCount)])).sort((a, b) => a - b) : [1];
  const isRunoffVote = Boolean(room?.runoffCandidateIds?.length);
  const runoffCandidateNames = room?.runoffCandidateIds?.map((id) => room.players.find((player) => player.id === id)?.name).filter((name): name is string => Boolean(name)).join("、") ?? "";
  const roundProgressLabel = room?.runoffCandidateIds?.length && room.currentRound > room.roundsTotal ? "追加" : room ? `${room.currentRound}/${room.roundsTotal}` : "";
  const { secondsLeft: turnSecondsLeft } = useWordWolfPhaseClock({ phase: room?.phase, configuredSeconds: room?.turnTimeLimitSeconds ?? 0, startedAt: room?.currentTurnStartedAt, limitSecondsOverride: room && currentPlayer?.id && room.playerTimeouts[currentPlayer.id]?.reducedTime && room.phase !== "lobby" && room.phase !== "result" ? reducedPlayerTimeLimitSeconds : undefined });
  const shouldShowClueLog = Boolean(room && room.phase !== "lobby" && (room.clueLogVisibility === "always" || room.clueMode === "simultaneous" || room.phase === "result"));
  return { activePlayer, currentPlayer, wolfIds, wolfPlayers, accusedPlayer, accusedIsWolf, finalAnswerPlayer, nextVotePlayer, isDebugMode, clueActor, voteActor, voteDisplayPlayer, guessActor, isHost, headerName, headerAvatarColor, headerAvatarImage, ownWord, resultTitle, topicSourceLabel, voteVoters, votedCount, selectedVoteTargetId, clueParticipants, clueSubmittedCount, canSubmitClue, voteCandidates, allowedWolfCount, wolfCountOptions, isRunoffVote, runoffCandidateNames, roundProgressLabel, turnSecondsLeft, shouldShowClueLog, hasWolfInCurrentGame: wolfIds.length > 0, isMyClueTurn: Boolean(room?.phase === "clue" && canSubmitClue), isMyVoteTurn: Boolean(room?.phase === "vote" && voteActor), isMyFinalAnswerTurn: Boolean(room?.phase === "wolfGuess" && room.accusedId && guessActor?.id === room.accusedId && accusedIsWolf), clueActorId: clueActor?.id ?? "", currentPlayerId: currentPlayer?.id ?? "", guessActorId: guessActor?.id ?? "" };
}
